[workspace]

[package]
name = "test_log_support"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
tracing = { path = "..", features = ["log"] }
log = { version = "0.4", features = ["std"] }
