[workspace]

members = [
    "tokio-trace-proc-macros",
    "tokio-trace-fmt",
    "tokio-trace-futures",
    "tokio-trace-tower",
    "tokio-trace-tower-http",
    "tokio-trace-log",
    "tokio-trace-env-logger",
    "tokio-trace-slog",
    "tokio-trace-macros",
    "tokio-trace-subscriber"
]

[patch.crates-io]
tokio-trace = { git = "https://github.com/tokio-rs/tokio" }
