[workspace]

members = [
    "tracing",
    "tracing-core",
    "tracing-proc-macros",
    "tracing-fmt",
    "tracing-futures",
    "tracing-tower",
    "tracing-tower-http",
    "tracing-log",
    "tracing-env-logger",
    "tracing-slog",
    "tracing-macros",
    "tracing-subscriber",
    "tracing-serde",
]
