[package]
name = "tracing-tower"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[dependencies]
tracing = { version = "0.1", path = "../tracing" }
tracing-futures = { path = "../tracing-futures" }
futures = "0.1"
tower-service = "0.2"
