[package]
name = "tracing-slog"
version = "0.1.0"
authors = ["David Barsky <dbarsky@amazon.com>"]

[dependencies.tracing]
# TODO: replace this with a path dependency on the local `tracing`.
package = "tokio-trace"
version = "0.1"
