[package]
name = "tracing-fmt"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]

[features]
default = ["ansi", "chrono"]
ansi = ["ansi_term"]

[dependencies]
ansi_term = { version = "0.11", optional = true }
regex = "1"
lazy_static = "1"
owning_ref = "0.4.0"
parking_lot = { version = "0.7"}
lock_api = "0.1"
chrono = { version = "0.4", optional = true }

[dependencies.tracing-core]
# TODO: replace this with a path dependency on the local `tracing-core`.
package = "tokio-trace-core"
version = "0.2.0"

[dev-dependencies.tracing]
# TODO: replace this with a path dependency on the local `tracing`.
package = "tokio-trace"
version = "0.1"
