[package]
name = "tracing-futures"
version = "0.0.1-alpha.1"
authors = ["Eliza Weisman <eliza@buoyant.io>", "Tokio Contributors <team@tokio.rs>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
documentation = "https://docs.rs/tracing-futures/0.0.1-alpha.1/tracing_futures"
readme = "README.md"
homepage = "https://tokio.rs"
description = """
Utilities for instrumenting `futures` with `tracing`.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing", "futures"]
license = "MIT"

[features]
default = ["futures-01", "tokio"]
futures-01 = ["futures"]
std-future = ["pin-utils"]

[dependencies]
futures = { version = "0.1", optional = true }
pin-utils = { version = "0.1.0-alpha.4", optional = true }
tracing = "0.1"
tokio = { version = "0.1", optional = true }
tokio-executor = { version = "0.1", optional = true }

[dev-dependencies]
tokio = "0.1.22"
tracing-fmt = "0.0.1-alpha.2"
tracing-core = "0.1.2"

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "experimental" }
