[package]
name = "tracing-log"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tracing-log/0.0.1/tracing_log"
description = """
Provides compatibility between `tracing` and `log` crate
"""
categories = [
    "development-tools::debugging",
    "asynchronous",
]
keywords = ["logging", "tracing"]
license = "MIT"

[dependencies]
tracing-core = "0.1.2"
tracing-subscriber = { path = "../tracing-subscriber" }
log = { version = "0.4", features = ["std"] }
lazy_static = "1.3.0"

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "experimental" }
