[package]
name = "tokio-trace-serde"
version = "0.1.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"

[dependencies]
serde = "1"
tokio-trace-core = "0.2.0"

[dev-dependencies]
serde_json = "1.0"
tokio-trace = "0.1"
