[package]
name = "tracing-subscriber"
version = "0.0.1-alpha.2"
authors = ["Eliza Weisman <eliza@buoyant.io>", "Tokio Contributors <team@tokio.rs>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tracing-subscriber/0.0.1-alpha.2/tracing-subscriber"
description = """
Utilities for implementing and composing `tracing` subscribers.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing", "metrics", "subscriber"]

[features]
default = ["filter", "smallvec"]
filter = ["matchers", "regex", "lazy_static"]

[dependencies]
tracing-core = "0.1.2"
crossbeam-utils = "0.6"

# only required by the filter feature
matchers = { optional = true, version = "0.0.1" }
regex = { optional = true, version = "1" }
smallvec = { optional = true, version = "0.6.10"}
lazy_static = { optional = true, version = "1" }

[dev-dependencies]
tracing-fmt = "0.0.1-alpha.2"
tracing = "0.1"

# load generator demo
tracing-tower = { path = "../tracing-tower" }
tower = "0.1"
tower-hyper = "0.1"
tower-http-util = "0.1"
tracing-futures = "0.0.1-alpha.1"
futures = "0.1"
hyper = "0.12"
tokio = "0.1"
tokio-tcp = "0.1"
tokio-buf = "0.1"
rand = "0.6"

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "experimental" }
