name: CI

on: [push]

jobs:
  check: 
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Check
      run: cargo check --all

  build:
    needs: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
